name: shit...
on:
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours
  workflow_dispatch:

jobs:
  check-irc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4



      - name: Run Check
        run: |
          chmod +x bash.sh
          ./bash.sh
